import { jsPDF } from 'jspdf';

export class PDFService {
  private static instance: PDFService;
  
  static getInstance(): PDFService {
    if (!this.instance) {
      this.instance = new PDFService();
    }
    return this.instance;
  }

  async generateConversationPDF(
    conversationTitle: string,
    messages: Array<{role: string, content: string, timestamp: string}>,
    shareUrl: string
  ): Promise<Buffer> {
    try {
      console.log('Starting PDF generation for conversation:', conversationTitle);
      
      // Create a new PDF document
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });
      
      // Set up fonts and colors
      pdf.setFont('helvetica');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - (margin * 2);
      let yPosition = margin;
      
      // Title
      pdf.setFontSize(20);
      pdf.setTextColor(75, 0, 130); // Purple
      pdf.text('🌟 Cosmic Chat Conversation', margin, yPosition);
      yPosition += 15;
      
      // Subtitle
      pdf.setFontSize(12);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPosition);
      yPosition += 8;
      
      // Clickable share URL
      pdf.setTextColor(0, 0, 255); // Blue color for link
      const linkText = '🔗 Click here to view live conversation';
      pdf.text(linkText, margin, yPosition);
      
      // Add clickable link annotation
      const textWidth = pdf.getTextWidth(linkText);
      pdf.link(margin, yPosition - 4, textWidth, 8, { url: shareUrl });
      yPosition += 15;
      
      // Separator line
      pdf.setDrawColor(75, 0, 130);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;
      
      // Messages
      pdf.setFontSize(10);
      for (const message of messages) {
        // Check if we need a new page
        if (yPosition > pageHeight - 40) {
          pdf.addPage();
          yPosition = margin;
        }
        
        const timestamp = new Date(message.timestamp).toLocaleString();
        const role = message.role === 'user' ? '👤 You' : '🌌 Cosmic AI';
        
        // Role and timestamp
        pdf.setTextColor(75, 0, 130);
        pdf.setFont('helvetica', 'bold');
        pdf.text(`${role} - ${timestamp}`, margin, yPosition);
        yPosition += 6;
        
        // Message content
        pdf.setTextColor(50, 50, 50);
        pdf.setFont('helvetica', 'normal');
        
        // Split long messages into multiple lines
        const messageLines = pdf.splitTextToSize(message.content, contentWidth);
        pdf.text(messageLines, margin, yPosition);
        yPosition += messageLines.length * 4 + 8;
        
        // Separator
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 8;
      }
      
      // Footer
      yPosition = Math.max(yPosition, pageHeight - 40);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Cosmic Music Curator - Your AI-powered astrological music companion', margin, yPosition);
      yPosition += 8;
      
      // Add clickable footer link
      pdf.setTextColor(0, 0, 255);
      const footerLinkText = `Visit conversation: ${shareUrl}`;
      pdf.text(footerLinkText, margin, yPosition);
      
      // Add clickable link annotation for footer
      const footerTextWidth = pdf.getTextWidth(footerLinkText);
      pdf.link(margin, yPosition - 4, footerTextWidth, 8, { url: shareUrl });
      
      // Convert to buffer
      const pdfBuffer = Buffer.from(pdf.output('arraybuffer'));
      
      console.log('PDF generated successfully, size:', pdfBuffer.length);
      
      return pdfBuffer;
    } catch (error: any) {
      console.error('PDF generation error details:', {
        error: error?.message || String(error),
        stack: error?.stack,
        name: error?.name
      });
      throw new Error(`Failed to generate PDF: ${error?.message || String(error)}`);
    }
  }

  private generateSimplePDFContent(
    title: string,
    messages: Array<{role: string, content: string, timestamp: string}>,
    shareUrl: string
  ): string {
    const date = new Date().toLocaleDateString();
    
    let content = `COSMIC CHAT CONVERSATION\n`;
    content += `=========================\n\n`;
    content += `Title: ${title}\n`;
    content += `Generated: ${date}\n`;
    content += `Share URL: ${shareUrl}\n\n`;
    content += `CONVERSATION HISTORY\n`;
    content += `===================\n\n`;
    
    messages.forEach((message, index) => {
      const timestamp = new Date(message.timestamp).toLocaleString();
      const role = message.role === 'user' ? 'YOU' : 'COSMIC AI';
      
      content += `[${timestamp}] ${role}:\n`;
      content += `${message.content}\n\n`;
      content += `${'─'.repeat(50)}\n\n`;
    });
    
    content += `\n\nGenerated by Cosmic Music Curator\n`;
    content += `Your AI-powered astrological music companion\n`;
    
    return content;
  }

  private generateConversationHTML(
    title: string,
    messages: Array<{role: string, content: string, timestamp: string}>,
    shareUrl: string
  ): string {
    const messageCount = {
      user: messages.filter(m => m.role === 'user').length,
      assistant: messages.filter(m => m.role === 'assistant').length
    };

    const messagesHTML = messages.map((message, index) => {
      const isUser = message.role === 'user';
      const date = new Date(message.timestamp).toLocaleDateString();
      
      return `
        <div class="message ${isUser ? 'user' : 'assistant'}">
          <div class="message-header">
            <span class="role-icon">${isUser ? '🌟' : '🔮'}</span>
            <span class="role-name">${isUser ? 'You asked:' : 'Cosmic AI responded:'}</span>
            <span class="timestamp">${date}</span>
          </div>
          <div class="message-content">
            ${message.content.replace(/\n/g, '<br>')}
          </div>
        </div>
      `;
    }).join('');

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${title} - Cosmic Conversation</title>
          <style>
            * {
              margin: 0;
              padding: 0;
              box-sizing: border-box;
            }
            
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
              line-height: 1.6;
              color: #1a1a1a;
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              min-height: 100vh;
              padding: 20px;
            }
            
            .container {
              max-width: 800px;
              margin: 0 auto;
              background: white;
              border-radius: 20px;
              padding: 40px;
              box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            }
            
            .header {
              text-align: center;
              margin-bottom: 40px;
              padding-bottom: 30px;
              border-bottom: 2px solid #f0f0f0;
            }
            
            .title {
              font-size: 2.5rem;
              font-weight: bold;
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              -webkit-background-clip: text;
              -webkit-text-fill-color: transparent;
              background-clip: text;
              margin-bottom: 10px;
            }
            
            .subtitle {
              color: #666;
              font-size: 1.1rem;
              margin-bottom: 20px;
            }
            
            .stats {
              display: flex;
              justify-content: center;
              gap: 30px;
              margin-top: 20px;
              flex-wrap: wrap;
            }
            
            .stat {
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              color: white;
              padding: 10px 20px;
              border-radius: 25px;
              font-size: 0.9rem;
              font-weight: 600;
            }
            
            .conversation {
              margin-top: 40px;
            }
            
            .section-title {
              font-size: 1.5rem;
              color: #333;
              margin-bottom: 30px;
              text-align: center;
              font-weight: 600;
            }
            
            .message {
              margin-bottom: 30px;
              border-radius: 15px;
              padding: 25px;
              position: relative;
              page-break-inside: avoid;
            }
            
            .message.user {
              background: linear-gradient(135deg, #667eea15 0%, #764ba215 100%);
              border-left: 4px solid #667eea;
            }
            
            .message.assistant {
              background: linear-gradient(135deg, #48bb7815 0%, #48bb7815 100%);
              border-left: 4px solid #48bb78;
            }
            
            .message-header {
              display: flex;
              align-items: center;
              margin-bottom: 15px;
              gap: 10px;
            }
            
            .role-icon {
              font-size: 1.2rem;
            }
            
            .role-name {
              font-weight: 600;
              color: #333;
              font-size: 0.9rem;
            }
            
            .timestamp {
              margin-left: auto;
              font-size: 0.8rem;
              color: #666;
            }
            
            .message-content {
              line-height: 1.7;
              color: #444;
            }
            
            .footer {
              margin-top: 60px;
              padding-top: 30px;
              border-top: 2px solid #f0f0f0;
              text-align: center;
              color: #666;
            }
            
            .share-url {
              background: #f8f9fa;
              padding: 15px;
              border-radius: 10px;
              font-family: monospace;
              font-size: 0.9rem;
              word-break: break-all;
              margin: 15px 0;
            }
            
            .share-link {
              color: #667eea;
              text-decoration: none;
              font-weight: 600;
            }
            
            .share-link:hover {
              text-decoration: underline;
            }
            
            .logo {
              font-size: 2rem;
              margin-bottom: 10px;
            }
            
            @media print {
              body {
                background: white !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
              }
            }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <div class="logo">🌟</div>
              <h1 class="title">${title}</h1>
              <p class="subtitle">A cosmic conversation exploring Astrology & You</p>
              <div class="stats">
                <div class="stat">${messageCount.user} questions</div>
                <div class="stat">${messageCount.assistant} cosmic responses</div>
                <div class="stat">${new Date().toLocaleDateString()} exported</div>
              </div>
            </div>
            
            <div class="conversation">
              <h2 class="section-title">✨ Complete Conversation</h2>
              ${messagesHTML}
            </div>
            
            <div class="footer">
              <div class="logo">🌟</div>
              <p><strong>Cosmic Playlist Generator</strong></p>
              <p>AI-powered astrological music curation</p>
              <div class="share-url">
                <a href="${shareUrl}" class="share-link" target="_blank">🔗 Click here to view live conversation</a>
              </div>
              <p>Generated on ${new Date().toLocaleDateString()} • <a href="${shareUrl}" class="share-link" target="_blank">Click the link above</a> to experience the interactive version</p>
            </div>
          </div>
        </body>
      </html>
    `;
  }

  async generateChartPDF(options: {
    userName: string;
    birthDate: string;
    birthTime: string;
    birthLocation: string;
    chartData: any;
    svgContent?: string;
    includeHouses?: boolean;
  }): Promise<Buffer> {
    try {
      console.log('Starting chart PDF generation for:', options.userName);
      
      // Create a new PDF document
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });
      
      // Set up fonts and colors
      pdf.setFont('helvetica');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - (margin * 2);
      let yPosition = margin;
      
      // Title
      pdf.setFontSize(22);
      pdf.setTextColor(75, 0, 130); // Purple
      pdf.text(`🌟 ${options.userName}'s Birth Chart`, margin, yPosition);
      yPosition += 15;
      
      // Birth details
      pdf.setFontSize(12);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Birth Date: ${options.birthDate}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Birth Time: ${options.birthTime}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Birth Location: ${options.birthLocation}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPosition);
      yPosition += 15;
      
      // Separator line
      pdf.setDrawColor(75, 0, 130);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 15;
      
      // Big Three Section
      if (options.chartData) {
        pdf.setFontSize(16);
        pdf.setTextColor(75, 0, 130);
        pdf.text('✨ The Big Three', margin, yPosition);
        yPosition += 12;
        
        pdf.setFontSize(12);
        pdf.setTextColor(50, 50, 50);
        if (options.chartData.sunSign) {
          pdf.text(`☀️ Sun Sign: ${options.chartData.sunSign}`, margin, yPosition);
          yPosition += 8;
        }
        if (options.chartData.moonSign) {
          pdf.text(`🌙 Moon Sign: ${options.chartData.moonSign}`, margin, yPosition);
          yPosition += 8;
        }
        if (options.chartData.rising) {
          pdf.text(`⬆️ Rising Sign: ${options.chartData.rising}`, margin, yPosition);
          yPosition += 8;
        }
        yPosition += 10;
        
        // Planetary Positions
        if (options.chartData.planets && options.chartData.planets.length > 0) {
          pdf.setFontSize(16);
          pdf.setTextColor(75, 0, 130);
          pdf.text('🪐 Planetary Positions', margin, yPosition);
          yPosition += 12;
          
          pdf.setFontSize(10);
          pdf.setTextColor(50, 50, 50);
          
          for (const planet of options.chartData.planets) {
            if (yPosition > pageHeight - 20) {
              pdf.addPage();
              yPosition = margin;
            }
            
            const planetText = `${planet.planet}: ${planet.sign} (${planet.degree}°) in House ${planet.house}`;
            pdf.text(planetText, margin, yPosition);
            yPosition += 6;
          }
          yPosition += 10;
        }
        
        // Houses section if requested
        if (options.includeHouses && options.chartData.houses) {
          pdf.setFontSize(16);
          pdf.setTextColor(75, 0, 130);
          pdf.text('🏠 Astrological Houses', margin, yPosition);
          yPosition += 12;
          
          pdf.setFontSize(10);
          pdf.setTextColor(50, 50, 50);
          
          for (const house of options.chartData.houses) {
            if (yPosition > pageHeight - 20) {
              pdf.addPage();
              yPosition = margin;
            }
            
            const houseText = `House ${house.number} (${house.sign}): ${house.themes?.join(', ') || 'Life themes'}`;
            const lines = pdf.splitTextToSize(houseText, contentWidth);
            pdf.text(lines, margin, yPosition);
            yPosition += lines.length * 6 + 3;
          }
          yPosition += 10;
        }
        
        // Element Balance
        if (options.chartData.elementBalance) {
          pdf.setFontSize(14);
          pdf.setTextColor(75, 0, 130);
          pdf.text('🌟 Element Balance', margin, yPosition);
          yPosition += 10;
          
          pdf.setFontSize(10);
          pdf.setTextColor(50, 50, 50);
          
          Object.entries(options.chartData.elementBalance).forEach(([element, count]: [string, any]) => {
            pdf.text(`${element}: ${count}`, margin, yPosition);
            yPosition += 6;
          });
          yPosition += 10;
        }
      }
      
      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Cosmic Music Curator', margin, pageHeight - 10);
      
      return Buffer.from(pdf.output('arraybuffer'));
    } catch (error: any) {
      console.error('Chart PDF generation error:', error, {
        message: error?.message,
        stack: error?.stack,
        name: error?.name
      });
      throw new Error(`Failed to generate chart PDF: ${error?.message || String(error)}`);
    }
  }
}

export const pdfService = PDFService.getInstance();